#!/usr/bin/env python
import sys
gro = sys.argv[1]
out = open('rec_solv_clear.gro', 'w')
lst = [float(line[36:44].strip()) for line in open(gro, 'r') if len(line) == 45 \
      and line[5:10].rstrip() == 'POPC']
zma = max(lst)
zmi = min(lst)
print(zmi, zma)

nid = []
i   = 0
j   = 0
k   = 0
hw  = 0
tes = 'NULL'

for line in open(gro, 'r'):
   if len(line) == 45:   # for the gro file generated by gmx5, no velocity
      rid = int(line[0:5].strip())
      res = line[5:10].rstrip()
      atm = line[10:15].strip()
      #aid = int(line[15:20].strip())
      x   = float(line[20:28].strip())
      y   = float(line[28:36].strip())
      z   = float(line[36:44].strip())

      if rid == hw and atm[0:2] == 'HW' and res == tes:
         continue

      if res in ['SOL', 'HOH'] and atm == 'OW':
         if z < zma and z > zmi:
            i  += 1
            hw  = rid
            tes = res
            #print('removing water molecule ' + str(i))
            deW = i
            continue

      j   += 1
      k   += 1
      #wid  = rid
      #if res in ['SOL', 'HOH']:
      #   wid -= i
      if j > 99999:
         j = j - 99999
      xyz  = '%5d%-5s%5s%5d%8.3f%8.3f%8.3f' % (rid, res, atm, j, x, y, z)
      nid.append(xyz)
   else:
      box = line # standard gro file

print('Number of removed Water molecules: ' + str(deW))
out.write('Water molecules in the lipid layer were removed\n')
out.write(str(k) + '\n')
out.write('\n'.join(nid))
out.write('\n' + box)
out.close()
